name:          SQL style guide by Simon Holywell
description:   A consistent code style guide for SQL to ensure legible and maintainable projects

ga_ua_code: UA-65071829-1

url:           http://www.sqlstyle.guide
domain:        sqlstyle.guide
port:          4040

markdown:      kramdown
permalink:     pretty
highlighter:   rouge

kramdown:
    input: GFM
    hard_wrap: false
    toc_levels: "2,3"

gems:
    - jekyll-redirect-from
